/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app-dashboard'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as NexaRouteImport } from './routes/nexa'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app-dashboard',
  path: '/app-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const NexaRoute = NexaRouteImport.update({
  id: '/nexa',
  path: '/nexa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-dashboard': typeof AppDashboardRoute
  '/connection': typeof ConnectionRoute
  '/dashboard': typeof DashboardRoute
  '/environment': typeof EnvironmentRoute
  '/nexa': typeof NexaRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-dashboard': typeof AppDashboardRoute
  '/connection': typeof ConnectionRoute
  '/dashboard': typeof DashboardRoute
  '/environment': typeof EnvironmentRoute
  '/nexa': typeof NexaRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-dashboard': typeof AppDashboardRoute
  '/connection': typeof ConnectionRoute
  '/dashboard': typeof DashboardRoute
  '/environment': typeof EnvironmentRoute
  '/nexa': typeof NexaRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-dashboard'
    | '/connection'
    | '/dashboard'
    | '/environment'
    | '/nexa'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-dashboard'
    | '/connection'
    | '/dashboard'
    | '/environment'
    | '/nexa'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/app-dashboard'
    | '/connection'
    | '/dashboard'
    | '/environment'
    | '/nexa'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppDashboardRoute: typeof AppDashboardRoute
  ConnectionRoute: typeof ConnectionRoute
  DashboardRoute: typeof DashboardRoute
  EnvironmentRoute: typeof EnvironmentRoute
  NexaRoute: typeof NexaRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-dashboard': {
      id: '/app-dashboard'
      path: '/app-dashboard'
      fullPath: '/app-dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexa': {
      id: '/nexa'
      path: '/nexa'
      fullPath: '/nexa'
      preLoaderRoute: typeof NexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppDashboardRoute: AppDashboardRoute,
  ConnectionRoute: ConnectionRoute,
  DashboardRoute: DashboardRoute,
  EnvironmentRoute: EnvironmentRoute,
  NexaRoute: NexaRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
